# Site
name: "Luqmansen's Blog"
title: "Luqmansen's Blog"
description: "Random thoughts and some computer stuff"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-193107374-1'

disqus: 'luqmansen'
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  luqmansen:
    name: luqmansen
    display_name: Luqman
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: luqmansen@gmail.com
    web: https://luqmansen.github.io
    description: "A normal person, trying to love what he's doing"
  

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 21
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [vendor, changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
