name: Build Blog

on:
  schedule:
  - cron: "0 23 * * *"
  push:

permissions:
    contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Generate the test blog
        run: |
          npm i -g notablog
          notablog generate .

          rm -rf docs
          mkdir -p docs
          cp public/. docs/
          
          git config user.name github-actions
          git config user.email github-actions@github.com
          git status
          git add .
          git commit -m "generated the blog"
          git push

        env:
          CI: true

    
